php_version: 8.2
global_exclude_dirs:
    - vendor
    - tests
rules:
    php.use_exit_function:
        enabled: true
        ignore_files:
            - src/makeFont.php
            - create_phar.php
    php.use_global_variable_or_function:
        enabled: true
        ignore_files:
            - create_phar.php
